> Purpose: Tenant schema DDL
> Audience: founders and coding agents
> Prerequisites: `docs/00-INDEX.md`, `docs/DECISIONS.md`, `docs/SYMBOL_REGISTRY.md`
> Owner lane: A
> Last verified against SYMBOL_REGISTRY version: v1

-- Supabase CLI migration source. Timestamp and lane prefix are assigned in migration-plan.md.
CREATE SCHEMA IF NOT EXISTS private;
CREATE TABLE IF NOT EXISTS public.departments(id uuid NOT NULL DEFAULT gen_random_uuid(), university_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, name text NOT NULL, slug text NOT NULL, CONSTRAINT departments_pkey PRIMARY KEY(id), CONSTRAINT departments_tenant_id_key UNIQUE(university_id,id), CONSTRAINT departments_university_fk FOREIGN KEY(university_id) REFERENCES public.universities(id) ON DELETE RESTRICT);
CREATE INDEX IF NOT EXISTS departments_tenant_created_idx ON public.departments(university_id,created_at DESC);
CREATE INDEX IF NOT EXISTS departments_creator_idx ON public.departments(university_id,created_by) WHERE created_by IS NOT NULL;
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY; ALTER TABLE public.departments FORCE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION private.touch_departments() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN NEW.updated_at:=now(); RETURN NEW; END $$;
DROP TRIGGER IF EXISTS departments_touch ON public.departments; CREATE TRIGGER departments_touch BEFORE UPDATE ON public.departments FOR EACH ROW EXECUTE FUNCTION private.touch_departments();
CREATE TABLE IF NOT EXISTS public.terms(id uuid NOT NULL DEFAULT gen_random_uuid(), university_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, name text NOT NULL, starts_on date NOT NULL, ends_on date NOT NULL, publication_state text NOT NULL DEFAULT 'draft', CONSTRAINT terms_pkey PRIMARY KEY(id), CONSTRAINT terms_tenant_id_key UNIQUE(university_id,id), CONSTRAINT terms_university_fk FOREIGN KEY(university_id) REFERENCES public.universities(id) ON DELETE RESTRICT);
CREATE INDEX IF NOT EXISTS terms_tenant_created_idx ON public.terms(university_id,created_at DESC);
CREATE INDEX IF NOT EXISTS terms_creator_idx ON public.terms(university_id,created_by) WHERE created_by IS NOT NULL;
ALTER TABLE public.terms ENABLE ROW LEVEL SECURITY; ALTER TABLE public.terms FORCE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION private.touch_terms() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN NEW.updated_at:=now(); RETURN NEW; END $$;
DROP TRIGGER IF EXISTS terms_touch ON public.terms; CREATE TRIGGER terms_touch BEFORE UPDATE ON public.terms FOR EACH ROW EXECUTE FUNCTION private.touch_terms();
CREATE TABLE IF NOT EXISTS public.courses(id uuid NOT NULL DEFAULT gen_random_uuid(), university_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, department_id uuid, code text NOT NULL, title text NOT NULL, description text NOT NULL DEFAULT '', publication_state text NOT NULL DEFAULT 'draft', CONSTRAINT courses_pkey PRIMARY KEY(id), CONSTRAINT courses_tenant_id_key UNIQUE(university_id,id), CONSTRAINT courses_university_fk FOREIGN KEY(university_id) REFERENCES public.universities(id) ON DELETE RESTRICT, CONSTRAINT courses_department_id_tenant_fk FOREIGN KEY(university_id,department_id) REFERENCES public.departments(university_id,id) ON DELETE RESTRICT);
CREATE INDEX IF NOT EXISTS courses_tenant_created_idx ON public.courses(university_id,created_at DESC);
CREATE INDEX IF NOT EXISTS courses_creator_idx ON public.courses(university_id,created_by) WHERE created_by IS NOT NULL;
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY; ALTER TABLE public.courses FORCE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION private.touch_courses() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN NEW.updated_at:=now(); RETURN NEW; END $$;
DROP TRIGGER IF EXISTS courses_touch ON public.courses; CREATE TRIGGER courses_touch BEFORE UPDATE ON public.courses FOR EACH ROW EXECUTE FUNCTION private.touch_courses();
CREATE TABLE IF NOT EXISTS public.course_offerings(id uuid NOT NULL DEFAULT gen_random_uuid(), university_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, course_id uuid NOT NULL, term_id uuid NOT NULL, offering_code text NOT NULL, CONSTRAINT course_offerings_pkey PRIMARY KEY(id), CONSTRAINT course_offerings_tenant_id_key UNIQUE(university_id,id), CONSTRAINT course_offerings_university_fk FOREIGN KEY(university_id) REFERENCES public.universities(id) ON DELETE RESTRICT, CONSTRAINT course_offerings_course_id_tenant_fk FOREIGN KEY(university_id,course_id) REFERENCES public.courses(university_id,id) ON DELETE RESTRICT);
CREATE INDEX IF NOT EXISTS course_offerings_tenant_created_idx ON public.course_offerings(university_id,created_at DESC);
CREATE INDEX IF NOT EXISTS course_offerings_creator_idx ON public.course_offerings(university_id,created_by) WHERE created_by IS NOT NULL;
ALTER TABLE public.course_offerings ENABLE ROW LEVEL SECURITY; ALTER TABLE public.course_offerings FORCE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION private.touch_course_offerings() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN NEW.updated_at:=now(); RETURN NEW; END $$;
DROP TRIGGER IF EXISTS course_offerings_touch ON public.course_offerings; CREATE TRIGGER course_offerings_touch BEFORE UPDATE ON public.course_offerings FOR EACH ROW EXECUTE FUNCTION private.touch_course_offerings();
CREATE TABLE IF NOT EXISTS public.sections(id uuid NOT NULL DEFAULT gen_random_uuid(), university_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, offering_id uuid NOT NULL, section_code text NOT NULL, capacity integer, CONSTRAINT sections_pkey PRIMARY KEY(id), CONSTRAINT sections_tenant_id_key UNIQUE(university_id,id), CONSTRAINT sections_university_fk FOREIGN KEY(university_id) REFERENCES public.universities(id) ON DELETE RESTRICT, CONSTRAINT sections_offering_id_tenant_fk FOREIGN KEY(university_id,offering_id) REFERENCES public.course_offerings(university_id,id) ON DELETE RESTRICT);
CREATE INDEX IF NOT EXISTS sections_tenant_created_idx ON public.sections(university_id,created_at DESC);
CREATE INDEX IF NOT EXISTS sections_creator_idx ON public.sections(university_id,created_by) WHERE created_by IS NOT NULL;
ALTER TABLE public.sections ENABLE ROW LEVEL SECURITY; ALTER TABLE public.sections FORCE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION private.touch_sections() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN NEW.updated_at:=now(); RETURN NEW; END $$;
DROP TRIGGER IF EXISTS sections_touch ON public.sections; CREATE TRIGGER sections_touch BEFORE UPDATE ON public.sections FOR EACH ROW EXECUTE FUNCTION private.touch_sections();
CREATE TABLE IF NOT EXISTS public.enrollments(id uuid NOT NULL DEFAULT gen_random_uuid(), university_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, section_id uuid NOT NULL, profile_id uuid NOT NULL, status text NOT NULL DEFAULT 'active', CONSTRAINT enrollments_pkey PRIMARY KEY(id), CONSTRAINT enrollments_tenant_id_key UNIQUE(university_id,id), CONSTRAINT enrollments_university_fk FOREIGN KEY(university_id) REFERENCES public.universities(id) ON DELETE RESTRICT, CONSTRAINT enrollments_section_id_tenant_fk FOREIGN KEY(university_id,section_id) REFERENCES public.sections(university_id,id) ON DELETE RESTRICT);
CREATE INDEX IF NOT EXISTS enrollments_tenant_created_idx ON public.enrollments(university_id,created_at DESC);
CREATE INDEX IF NOT EXISTS enrollments_creator_idx ON public.enrollments(university_id,created_by) WHERE created_by IS NOT NULL;
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY; ALTER TABLE public.enrollments FORCE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION private.touch_enrollments() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN NEW.updated_at:=now(); RETURN NEW; END $$;
DROP TRIGGER IF EXISTS enrollments_touch ON public.enrollments; CREATE TRIGGER enrollments_touch BEFORE UPDATE ON public.enrollments FOR EACH ROW EXECUTE FUNCTION private.touch_enrollments();
CREATE TABLE IF NOT EXISTS public.offering_staff(id uuid NOT NULL DEFAULT gen_random_uuid(), university_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, offering_id uuid NOT NULL, profile_id uuid NOT NULL, staff_role text NOT NULL, CONSTRAINT offering_staff_pkey PRIMARY KEY(id), CONSTRAINT offering_staff_tenant_id_key UNIQUE(university_id,id), CONSTRAINT offering_staff_university_fk FOREIGN KEY(university_id) REFERENCES public.universities(id) ON DELETE RESTRICT);
CREATE INDEX IF NOT EXISTS offering_staff_tenant_created_idx ON public.offering_staff(university_id,created_at DESC);
CREATE INDEX IF NOT EXISTS offering_staff_creator_idx ON public.offering_staff(university_id,created_by) WHERE created_by IS NOT NULL;
ALTER TABLE public.offering_staff ENABLE ROW LEVEL SECURITY; ALTER TABLE public.offering_staff FORCE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION private.touch_offering_staff() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN NEW.updated_at:=now(); RETURN NEW; END $$;
DROP TRIGGER IF EXISTS offering_staff_touch ON public.offering_staff; CREATE TRIGGER offering_staff_touch BEFORE UPDATE ON public.offering_staff FOR EACH ROW EXECUTE FUNCTION private.touch_offering_staff();
CREATE TABLE IF NOT EXISTS public.grading_scales(id uuid NOT NULL DEFAULT gen_random_uuid(), university_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, name text NOT NULL, scale_type text NOT NULL, definition jsonb NOT NULL, CONSTRAINT grading_scales_pkey PRIMARY KEY(id), CONSTRAINT grading_scales_tenant_id_key UNIQUE(university_id,id), CONSTRAINT grading_scales_university_fk FOREIGN KEY(university_id) REFERENCES public.universities(id) ON DELETE RESTRICT);
CREATE INDEX IF NOT EXISTS grading_scales_tenant_created_idx ON public.grading_scales(university_id,created_at DESC);
CREATE INDEX IF NOT EXISTS grading_scales_creator_idx ON public.grading_scales(university_id,created_by) WHERE created_by IS NOT NULL;
ALTER TABLE public.grading_scales ENABLE ROW LEVEL SECURITY; ALTER TABLE public.grading_scales FORCE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION private.touch_grading_scales() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN NEW.updated_at:=now(); RETURN NEW; END $$;
DROP TRIGGER IF EXISTS grading_scales_touch ON public.grading_scales; CREATE TRIGGER grading_scales_touch BEFORE UPDATE ON public.grading_scales FOR EACH ROW EXECUTE FUNCTION private.touch_grading_scales();
CREATE TABLE IF NOT EXISTS public.assessments(id uuid NOT NULL DEFAULT gen_random_uuid(), university_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, offering_id uuid NOT NULL, section_id uuid, title text NOT NULL, assessment_type text NOT NULL, total numeric(10,2) NOT NULL CHECK(total>0), weight numeric(7,4) NOT NULL CHECK(weight>=0), visibility text NOT NULL DEFAULT 'private', CONSTRAINT assessments_pkey PRIMARY KEY(id), CONSTRAINT assessments_tenant_id_key UNIQUE(university_id,id), CONSTRAINT assessments_university_fk FOREIGN KEY(university_id) REFERENCES public.universities(id) ON DELETE RESTRICT, CONSTRAINT assessments_offering_id_tenant_fk FOREIGN KEY(university_id,offering_id) REFERENCES public.course_offerings(university_id,id) ON DELETE RESTRICT);
CREATE INDEX IF NOT EXISTS assessments_tenant_created_idx ON public.assessments(university_id,created_at DESC);
CREATE INDEX IF NOT EXISTS assessments_creator_idx ON public.assessments(university_id,created_by) WHERE created_by IS NOT NULL;
ALTER TABLE public.assessments ENABLE ROW LEVEL SECURITY; ALTER TABLE public.assessments FORCE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION private.touch_assessments() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN NEW.updated_at:=now(); RETURN NEW; END $$;
DROP TRIGGER IF EXISTS assessments_touch ON public.assessments; CREATE TRIGGER assessments_touch BEFORE UPDATE ON public.assessments FOR EACH ROW EXECUTE FUNCTION private.touch_assessments();
CREATE TABLE IF NOT EXISTS public.marks(id uuid NOT NULL DEFAULT gen_random_uuid(), university_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, assessment_id uuid NOT NULL, student_id uuid NOT NULL, score numeric(10,2), status text NOT NULL DEFAULT 'pending', UNIQUE(university_id,assessment_id,student_id), CONSTRAINT marks_pkey PRIMARY KEY(id), CONSTRAINT marks_tenant_id_key UNIQUE(university_id,id), CONSTRAINT marks_university_fk FOREIGN KEY(university_id) REFERENCES public.universities(id) ON DELETE RESTRICT, CONSTRAINT marks_assessment_id_tenant_fk FOREIGN KEY(university_id,assessment_id) REFERENCES public.assessments(university_id,id) ON DELETE RESTRICT);
CREATE INDEX IF NOT EXISTS marks_tenant_created_idx ON public.marks(university_id,created_at DESC);
CREATE INDEX IF NOT EXISTS marks_creator_idx ON public.marks(university_id,created_by) WHERE created_by IS NOT NULL;
ALTER TABLE public.marks ENABLE ROW LEVEL SECURITY; ALTER TABLE public.marks FORCE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION private.touch_marks() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN NEW.updated_at:=now(); RETURN NEW; END $$;
DROP TRIGGER IF EXISTS marks_touch ON public.marks; CREATE TRIGGER marks_touch BEFORE UPDATE ON public.marks FOR EACH ROW EXECUTE FUNCTION private.touch_marks();
CREATE TABLE IF NOT EXISTS public.mark_history(id uuid NOT NULL DEFAULT gen_random_uuid(), university_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, mark_id uuid NOT NULL, actor_id uuid NOT NULL, old_score numeric(10,2), new_score numeric(10,2), reason text NOT NULL, source text NOT NULL CHECK(source IN ('manual','csv','objection')), CONSTRAINT mark_history_pkey PRIMARY KEY(id), CONSTRAINT mark_history_tenant_id_key UNIQUE(university_id,id), CONSTRAINT mark_history_university_fk FOREIGN KEY(university_id) REFERENCES public.universities(id) ON DELETE RESTRICT, CONSTRAINT mark_history_mark_id_tenant_fk FOREIGN KEY(university_id,mark_id) REFERENCES public.marks(university_id,id) ON DELETE RESTRICT);
CREATE INDEX IF NOT EXISTS mark_history_tenant_created_idx ON public.mark_history(university_id,created_at DESC);
CREATE INDEX IF NOT EXISTS mark_history_creator_idx ON public.mark_history(university_id,created_by) WHERE created_by IS NOT NULL;
ALTER TABLE public.mark_history ENABLE ROW LEVEL SECURITY; ALTER TABLE public.mark_history FORCE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION private.touch_mark_history() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN NEW.updated_at:=now(); RETURN NEW; END $$;
DROP TRIGGER IF EXISTS mark_history_touch ON public.mark_history; CREATE TRIGGER mark_history_touch BEFORE UPDATE ON public.mark_history FOR EACH ROW EXECUTE FUNCTION private.touch_mark_history();
CREATE TABLE IF NOT EXISTS public.import_batches(id uuid NOT NULL DEFAULT gen_random_uuid(), university_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, assessment_id uuid NOT NULL, created_by uuid NOT NULL, idempotency_key text NOT NULL, state text NOT NULL, expires_at timestamptz NOT NULL, UNIQUE(university_id,idempotency_key), CONSTRAINT import_batches_pkey PRIMARY KEY(id), CONSTRAINT import_batches_tenant_id_key UNIQUE(university_id,id), CONSTRAINT import_batches_university_fk FOREIGN KEY(university_id) REFERENCES public.universities(id) ON DELETE RESTRICT, CONSTRAINT import_batches_assessment_id_tenant_fk FOREIGN KEY(university_id,assessment_id) REFERENCES public.assessments(university_id,id) ON DELETE RESTRICT);
CREATE INDEX IF NOT EXISTS import_batches_tenant_created_idx ON public.import_batches(university_id,created_at DESC);
CREATE INDEX IF NOT EXISTS import_batches_creator_idx ON public.import_batches(university_id,created_by) WHERE created_by IS NOT NULL;
ALTER TABLE public.import_batches ENABLE ROW LEVEL SECURITY; ALTER TABLE public.import_batches FORCE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION private.touch_import_batches() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN NEW.updated_at:=now(); RETURN NEW; END $$;
DROP TRIGGER IF EXISTS import_batches_touch ON public.import_batches; CREATE TRIGGER import_batches_touch BEFORE UPDATE ON public.import_batches FOR EACH ROW EXECUTE FUNCTION private.touch_import_batches();
CREATE TABLE IF NOT EXISTS public.import_rows(id uuid NOT NULL DEFAULT gen_random_uuid(), university_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, batch_id uuid NOT NULL, row_number integer NOT NULL, row_hash text NOT NULL, email text, proposed_score numeric(10,2), status text NOT NULL, error_code text, CONSTRAINT import_rows_pkey PRIMARY KEY(id), CONSTRAINT import_rows_tenant_id_key UNIQUE(university_id,id), CONSTRAINT import_rows_university_fk FOREIGN KEY(university_id) REFERENCES public.universities(id) ON DELETE RESTRICT, CONSTRAINT import_rows_batch_id_tenant_fk FOREIGN KEY(university_id,batch_id) REFERENCES public.import_batches(university_id,id) ON DELETE RESTRICT);
CREATE INDEX IF NOT EXISTS import_rows_tenant_created_idx ON public.import_rows(university_id,created_at DESC);
CREATE INDEX IF NOT EXISTS import_rows_creator_idx ON public.import_rows(university_id,created_by) WHERE created_by IS NOT NULL;
ALTER TABLE public.import_rows ENABLE ROW LEVEL SECURITY; ALTER TABLE public.import_rows FORCE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION private.touch_import_rows() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN NEW.updated_at:=now(); RETURN NEW; END $$;
DROP TRIGGER IF EXISTS import_rows_touch ON public.import_rows; CREATE TRIGGER import_rows_touch BEFORE UPDATE ON public.import_rows FOR EACH ROW EXECUTE FUNCTION private.touch_import_rows();
CREATE TABLE IF NOT EXISTS public.announcements(id uuid NOT NULL DEFAULT gen_random_uuid(), university_id uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by uuid, section_id uuid NOT NULL, author_id uuid NOT NULL, title text NOT NULL, body_html text NOT NULL, CONSTRAINT announcements_pkey PRIMARY KEY(id), CONSTRAINT announcements_tenant_id_key UNIQUE(university_id,id), CONSTRAINT announcements_university_fk FOREIGN KEY(university_id) REFERENCES public.universities(id) ON DELETE RESTRICT);
CREATE INDEX IF NOT EXISTS announcements_tenant_created_idx ON public.announcements(university_id,created_at DESC);
CREATE INDEX IF NOT EXISTS announcements_creator_idx ON public.announcements(university_id,created_by) WHERE created_by IS NOT NULL;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY; ALTER TABLE public.announcements FORCE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION private.touch_announcements() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN NEW.updated_at:=now(); RETURN NEW; END $$;
DROP TRIGGER IF EXISTS announcements_touch ON public.announcements; CREATE TRIGGER announcements_touch BEFORE UPDATE ON public.announcements FOR EACH ROW EXECUTE FUNCTION private.touch_announcements();
-- Rollback only in a later expand/contract migration after consumers and data retention obligations are cleared.

## Self-check
- [x] Header and audience are stated.
- [x] Scope, tests, and operational constraints are present.
